"""Maivn Core - Core domain models and utilities for the Maivn platform.

This package provides the fundamental building blocks for Maivn applications:
- Domain entities (tools, sessions, messages, dependencies)
- Infrastructure (logging, HTTP client, API endpoints)
- Utilities
"""

from __future__ import annotations

from .core import (
    ASSIGNMENT_COMPLETED_EVENT_NAME,
    ASSIGNMENT_RECEIVED_EVENT_NAME,
    ENRICHMENT_EVENT_NAME,
    ERROR_EVENT_NAME,
    FINAL_EVENT_NAME,
    HEARTBEAT_EVENT_NAME,
    INTERRUPT_REQUEST_EVENT_NAME,
    INTERRUPT_REQUIRED_EVENT_NAME,
    MEMORY_ENRICHMENT_PHASES,
    MEMORY_GRAPH_EXTRACTING_ENRICHMENT_PHASE,
    MEMORY_INDEXED_ENRICHMENT_PHASE,
    MEMORY_INDEXING_ENRICHMENT_PHASE,
    MEMORY_INSIGHT_EXTRACTED_ENRICHMENT_PHASE,
    MEMORY_INSIGHT_EXTRACTING_ENRICHMENT_PHASE,
    MEMORY_RETRIEVED_ENRICHMENT_PHASE,
    MEMORY_RETRIEVING_ENRICHMENT_PHASE,
    MEMORY_SKILL_EXTRACTED_ENRICHMENT_PHASE,
    MEMORY_SKILL_EXTRACTING_ENRICHMENT_PHASE,
    MEMORY_SUMMARIZED_ENRICHMENT_PHASE,
    MEMORY_SUMMARIZING_ENRICHMENT_PHASE,
    MESSAGE_REDACTION_APPLIED_ENRICHMENT_PHASE,
    MODEL_TOOL_COMPLETE_EVENT_NAME,
    PROGRESS_UPDATE_EVENT_NAME,
    REDACTION_ENRICHMENT_PHASES,
    REDACTION_PREVIEWED_ENRICHMENT_PHASE,
    RESOURCE_DEDUP_REUSED_ENRICHMENT_PHASE,
    RESOURCE_ENRICHMENT_PHASES,
    RESOURCE_EXTRACTED_ENRICHMENT_PHASE,
    RESOURCE_EXTRACTING_ENRICHMENT_PHASE,
    RESOURCE_REGISTERED_ENRICHMENT_PHASE,
    RESOURCE_REGISTERING_ENRICHMENT_PHASE,
    RESOURCE_VERSION_SUPERSEDED_ENRICHMENT_PHASE,
    STATUS_MESSAGE_EVENT_NAME,
    SYSTEM_TOOL_CHUNK_EVENT_NAME,
    SYSTEM_TOOL_COMPLETE_EVENT_NAME,
    SYSTEM_TOOL_ERROR_EVENT_NAME,
    SYSTEM_TOOL_START_EVENT_NAME,
    TOOL_EVENT_NAME,
    UPDATE_EVENT_NAME,
    create_uuid,
)
from .domain.entities import (
    SWARM_AGENT_INVOCATION_METADATA_KEY,
    SWARM_INVOCATION_INTENT_METADATA_KEY,
    AgentDependency,
    AIMessage,
    ArgsSchema,
    AwaitForDependency,
    BaseDependency,
    BaseMessage,
    DataDependency,
    ExecutionInstanceControl,
    ExecutionTiming,
    HumanMessage,
    InterruptDependency,
    MemoryConfig,
    MemoryInsightExtractionConfig,
    MemoryLevel,
    MemoryPersistenceMode,
    MemoryRetrievalConfig,
    MemorySharingScope,
    MemorySkillExtractionConfig,
    PrivateData,
    RedactedMessage,
    RedactionPreviewRequest,
    RedactionPreviewResponse,
    ReevaluateDependency,
    SessionRequest,
    SessionResponse,
    SessionStartRequest,
    SessionStartupResponse,
    SystemMessage,
    ToolCall,
    ToolDependency,
    ToolExecutionResult,
    ToolMessage,
    ToolResumePayload,
    ToolSpec,
    ToolType,
)
from .domain.exceptions import (
    ConfigurationError,
    MaivnError,
    SerializationError,
    ValidationError,
    is_retryable,
    wrap_exception,
)
from .domain.factories import build_tool_spec_from_function
from .infrastructure import (
    HttpClient,
    HttpClientProtocol,
    HttpError,
    MaivnLogger,
    ServerEndpoints,
    SessionClientProtocol,
    SSEClientProtocol,
    get_logger,
    get_optional_logger,
)
from .infrastructure.logging import Colors, LogLevel, LogStyles
from .utils import (
    dumps,
    dumps_bytes,
    extract_tool_names,
    loads,
    serialize_error,
    serialize_with_metadata,
    to_jsonable,
)

__all__ = [
    # Core - Utilities
    "create_uuid",
    # Core - Events
    "TOOL_EVENT_NAME",
    "INTERRUPT_REQUEST_EVENT_NAME",
    "INTERRUPT_REQUIRED_EVENT_NAME",
    "ASSIGNMENT_RECEIVED_EVENT_NAME",
    "ASSIGNMENT_COMPLETED_EVENT_NAME",
    "MODEL_TOOL_COMPLETE_EVENT_NAME",
    "HEARTBEAT_EVENT_NAME",
    "UPDATE_EVENT_NAME",
    "PROGRESS_UPDATE_EVENT_NAME",
    "STATUS_MESSAGE_EVENT_NAME",
    "FINAL_EVENT_NAME",
    "ERROR_EVENT_NAME",
    "SYSTEM_TOOL_START_EVENT_NAME",
    "SYSTEM_TOOL_CHUNK_EVENT_NAME",
    "SYSTEM_TOOL_COMPLETE_EVENT_NAME",
    "SYSTEM_TOOL_ERROR_EVENT_NAME",
    "ENRICHMENT_EVENT_NAME",
    "MEMORY_SUMMARIZING_ENRICHMENT_PHASE",
    "MEMORY_SUMMARIZED_ENRICHMENT_PHASE",
    "MEMORY_RETRIEVING_ENRICHMENT_PHASE",
    "MEMORY_RETRIEVED_ENRICHMENT_PHASE",
    "MEMORY_INDEXING_ENRICHMENT_PHASE",
    "MEMORY_INDEXED_ENRICHMENT_PHASE",
    "MEMORY_GRAPH_EXTRACTING_ENRICHMENT_PHASE",
    "MEMORY_SKILL_EXTRACTING_ENRICHMENT_PHASE",
    "MEMORY_INSIGHT_EXTRACTING_ENRICHMENT_PHASE",
    "MEMORY_SKILL_EXTRACTED_ENRICHMENT_PHASE",
    "MEMORY_INSIGHT_EXTRACTED_ENRICHMENT_PHASE",
    "MEMORY_ENRICHMENT_PHASES",
    "MESSAGE_REDACTION_APPLIED_ENRICHMENT_PHASE",
    "REDACTION_PREVIEWED_ENRICHMENT_PHASE",
    "REDACTION_ENRICHMENT_PHASES",
    "RESOURCE_REGISTERING_ENRICHMENT_PHASE",
    "RESOURCE_REGISTERED_ENRICHMENT_PHASE",
    "RESOURCE_DEDUP_REUSED_ENRICHMENT_PHASE",
    "RESOURCE_VERSION_SUPERSEDED_ENRICHMENT_PHASE",
    "RESOURCE_EXTRACTING_ENRICHMENT_PHASE",
    "RESOURCE_EXTRACTED_ENRICHMENT_PHASE",
    "RESOURCE_ENRICHMENT_PHASES",
    # Domain - Entities - Memory Config
    "MemoryConfig",
    "MemoryInsightExtractionConfig",
    "MemoryLevel",
    "MemoryPersistenceMode",
    "MemoryRetrievalConfig",
    "MemorySharingScope",
    "MemorySkillExtractionConfig",
    # Domain - Entities - Session
    "SWARM_AGENT_INVOCATION_METADATA_KEY",
    "SWARM_INVOCATION_INTENT_METADATA_KEY",
    "RedactionPreviewRequest",
    "RedactionPreviewResponse",
    "SessionRequest",
    "SessionResponse",
    "SessionStartupResponse",
    "SessionStartRequest",
    # Domain - Entities - Tool Specification
    "ArgsSchema",
    "ToolSpec",
    "ToolType",
    "ToolCall",
    "ToolExecutionResult",
    # Domain - Entities - Messages
    "BaseMessage",
    "HumanMessage",
    "PrivateData",
    "RedactedMessage",
    "AIMessage",
    "SystemMessage",
    "ToolMessage",
    # Domain - Entities - Dependencies
    "BaseDependency",
    "AgentDependency",
    "AwaitForDependency",
    "DataDependency",
    "ExecutionInstanceControl",
    "ExecutionTiming",
    "InterruptDependency",
    "ReevaluateDependency",
    "ToolDependency",
    "ToolResumePayload",
    # Domain - Exceptions
    "MaivnError",
    "ConfigurationError",
    "ValidationError",
    "SerializationError",
    "wrap_exception",
    "is_retryable",
    # Domain - Factories
    "build_tool_spec_from_function",
    # Infrastructure - Logging
    "MaivnLogger",
    "LogLevel",
    "Colors",
    "LogStyles",
    "get_logger",
    "get_optional_logger",
    # Infrastructure - HTTP
    "HttpClient",
    "HttpError",
    "HttpClientProtocol",
    "SSEClientProtocol",
    "ServerEndpoints",
    "SessionClientProtocol",
    # Utilities - Serialization
    "dumps",
    "dumps_bytes",
    "loads",
    "to_jsonable",
    "serialize_error",
    "serialize_with_metadata",
    # Utilities - Tools
    "extract_tool_names",
]
