from __future__ import annotations

from maivn_shared import (
    MEMORY_ENRICHMENT_PHASES,
    MEMORY_GRAPH_EXTRACTING_ENRICHMENT_PHASE,
    MEMORY_INDEXED_ENRICHMENT_PHASE,
    MEMORY_INDEXING_ENRICHMENT_PHASE,
    MEMORY_INSIGHT_EXTRACTED_ENRICHMENT_PHASE,
    MEMORY_INSIGHT_EXTRACTING_ENRICHMENT_PHASE,
    MEMORY_RETRIEVED_ENRICHMENT_PHASE,
    MEMORY_RETRIEVING_ENRICHMENT_PHASE,
    MEMORY_SKILL_EXTRACTED_ENRICHMENT_PHASE,
    MEMORY_SKILL_EXTRACTING_ENRICHMENT_PHASE,
    MEMORY_SUMMARIZED_ENRICHMENT_PHASE,
    MEMORY_SUMMARIZING_ENRICHMENT_PHASE,
    RESOURCE_DEDUP_REUSED_ENRICHMENT_PHASE,
    RESOURCE_ENRICHMENT_PHASES,
    RESOURCE_EXTRACTED_ENRICHMENT_PHASE,
    RESOURCE_EXTRACTING_ENRICHMENT_PHASE,
    RESOURCE_REGISTERED_ENRICHMENT_PHASE,
    RESOURCE_REGISTERING_ENRICHMENT_PHASE,
    RESOURCE_VERSION_SUPERSEDED_ENRICHMENT_PHASE,
)


def test_memory_enrichment_phase_constants_are_stable() -> None:
    assert MEMORY_SUMMARIZING_ENRICHMENT_PHASE == "memory_summarizing"
    assert MEMORY_SUMMARIZED_ENRICHMENT_PHASE == "memory_summarized"
    assert MEMORY_RETRIEVING_ENRICHMENT_PHASE == "memory_retrieving"
    assert MEMORY_RETRIEVED_ENRICHMENT_PHASE == "memory_retrieved"
    assert MEMORY_INDEXING_ENRICHMENT_PHASE == "memory_indexing"
    assert MEMORY_INDEXED_ENRICHMENT_PHASE == "memory_indexed"
    assert MEMORY_GRAPH_EXTRACTING_ENRICHMENT_PHASE == "memory_graph_extracting"
    assert MEMORY_SKILL_EXTRACTING_ENRICHMENT_PHASE == "memory_skill_extracting"
    assert MEMORY_INSIGHT_EXTRACTING_ENRICHMENT_PHASE == "memory_insight_extracting"
    assert MEMORY_SKILL_EXTRACTED_ENRICHMENT_PHASE == "memory_skill_extracted"
    assert MEMORY_INSIGHT_EXTRACTED_ENRICHMENT_PHASE == "memory_insight_extracted"


def test_memory_enrichment_phase_registry_contains_all_memory_phases() -> None:
    assert MEMORY_ENRICHMENT_PHASES == (
        MEMORY_SUMMARIZING_ENRICHMENT_PHASE,
        MEMORY_SUMMARIZED_ENRICHMENT_PHASE,
        MEMORY_RETRIEVING_ENRICHMENT_PHASE,
        MEMORY_RETRIEVED_ENRICHMENT_PHASE,
        MEMORY_INDEXING_ENRICHMENT_PHASE,
        MEMORY_INDEXED_ENRICHMENT_PHASE,
        MEMORY_GRAPH_EXTRACTING_ENRICHMENT_PHASE,
        MEMORY_SKILL_EXTRACTING_ENRICHMENT_PHASE,
        MEMORY_INSIGHT_EXTRACTING_ENRICHMENT_PHASE,
        MEMORY_SKILL_EXTRACTED_ENRICHMENT_PHASE,
        MEMORY_INSIGHT_EXTRACTED_ENRICHMENT_PHASE,
    )


def test_resource_enrichment_phase_constants_are_stable() -> None:
    assert RESOURCE_REGISTERING_ENRICHMENT_PHASE == "resource_registering"
    assert RESOURCE_REGISTERED_ENRICHMENT_PHASE == "resource_registered"
    assert RESOURCE_DEDUP_REUSED_ENRICHMENT_PHASE == "resource_dedup_reused"
    assert RESOURCE_VERSION_SUPERSEDED_ENRICHMENT_PHASE == "resource_version_superseded"
    assert RESOURCE_EXTRACTING_ENRICHMENT_PHASE == "resource_extracting"
    assert RESOURCE_EXTRACTED_ENRICHMENT_PHASE == "resource_extracted"


def test_resource_enrichment_phase_registry_contains_all_resource_phases() -> None:
    assert RESOURCE_ENRICHMENT_PHASES == (
        RESOURCE_REGISTERING_ENRICHMENT_PHASE,
        RESOURCE_REGISTERED_ENRICHMENT_PHASE,
        RESOURCE_DEDUP_REUSED_ENRICHMENT_PHASE,
        RESOURCE_VERSION_SUPERSEDED_ENRICHMENT_PHASE,
        RESOURCE_EXTRACTING_ENRICHMENT_PHASE,
        RESOURCE_EXTRACTED_ENRICHMENT_PHASE,
    )
