"""Core application services and utilities for maivn-core."""

from __future__ import annotations

# MARK: - Utilities
from .data import create_uuid

# MARK: - Events
from .events import (
    ASSIGNMENT_COMPLETED_EVENT_NAME,
    # MARK: - Assignment Events
    ASSIGNMENT_RECEIVED_EVENT_NAME,
    # MARK: - Enrichment Events
    ENRICHMENT_EVENT_NAME,
    ERROR_EVENT_NAME,
    FINAL_EVENT_NAME,
    # MARK: - Lifecycle Events
    HEARTBEAT_EVENT_NAME,
    INTERRUPT_REQUEST_EVENT_NAME,
    INTERRUPT_REQUIRED_EVENT_NAME,
    MEMORY_ENRICHMENT_PHASES,
    MEMORY_GRAPH_EXTRACTING_ENRICHMENT_PHASE,
    MEMORY_INDEXED_ENRICHMENT_PHASE,
    MEMORY_INDEXING_ENRICHMENT_PHASE,
    MEMORY_INSIGHT_EXTRACTED_ENRICHMENT_PHASE,
    MEMORY_INSIGHT_EXTRACTING_ENRICHMENT_PHASE,
    MEMORY_RETRIEVED_ENRICHMENT_PHASE,
    MEMORY_RETRIEVING_ENRICHMENT_PHASE,
    MEMORY_SKILL_EXTRACTED_ENRICHMENT_PHASE,
    MEMORY_SKILL_EXTRACTING_ENRICHMENT_PHASE,
    MEMORY_SUMMARIZED_ENRICHMENT_PHASE,
    MEMORY_SUMMARIZING_ENRICHMENT_PHASE,
    MESSAGE_REDACTION_APPLIED_ENRICHMENT_PHASE,
    # MARK: - Model Events
    MODEL_TOOL_COMPLETE_EVENT_NAME,
    PROGRESS_UPDATE_EVENT_NAME,
    REDACTION_ENRICHMENT_PHASES,
    REDACTION_PREVIEWED_ENRICHMENT_PHASE,
    RESOURCE_DEDUP_REUSED_ENRICHMENT_PHASE,
    RESOURCE_ENRICHMENT_PHASES,
    RESOURCE_EXTRACTED_ENRICHMENT_PHASE,
    RESOURCE_EXTRACTING_ENRICHMENT_PHASE,
    RESOURCE_REGISTERED_ENRICHMENT_PHASE,
    RESOURCE_REGISTERING_ENRICHMENT_PHASE,
    RESOURCE_VERSION_SUPERSEDED_ENRICHMENT_PHASE,
    STATUS_MESSAGE_EVENT_NAME,
    SYSTEM_TOOL_CHUNK_EVENT_NAME,
    SYSTEM_TOOL_COMPLETE_EVENT_NAME,
    SYSTEM_TOOL_ERROR_EVENT_NAME,
    # MARK: - System Tool Events
    SYSTEM_TOOL_START_EVENT_NAME,
    # MARK: - Tool Events
    TOOL_EVENT_NAME,
    UPDATE_EVENT_NAME,
)

__all__ = [
    # MARK: - Utilities
    "create_uuid",
    # MARK: - Tool Events
    "TOOL_EVENT_NAME",
    "INTERRUPT_REQUEST_EVENT_NAME",
    "INTERRUPT_REQUIRED_EVENT_NAME",
    # MARK: - Assignment Events
    "ASSIGNMENT_RECEIVED_EVENT_NAME",
    "ASSIGNMENT_COMPLETED_EVENT_NAME",
    # MARK: - Model Events
    "MODEL_TOOL_COMPLETE_EVENT_NAME",
    # MARK: - Lifecycle Events
    "HEARTBEAT_EVENT_NAME",
    "UPDATE_EVENT_NAME",
    "PROGRESS_UPDATE_EVENT_NAME",
    "STATUS_MESSAGE_EVENT_NAME",
    "FINAL_EVENT_NAME",
    "ERROR_EVENT_NAME",
    # MARK: - System Tool Events
    "SYSTEM_TOOL_START_EVENT_NAME",
    "SYSTEM_TOOL_CHUNK_EVENT_NAME",
    "SYSTEM_TOOL_COMPLETE_EVENT_NAME",
    "SYSTEM_TOOL_ERROR_EVENT_NAME",
    # MARK: - Enrichment Events
    "ENRICHMENT_EVENT_NAME",
    "MEMORY_SUMMARIZING_ENRICHMENT_PHASE",
    "MEMORY_SUMMARIZED_ENRICHMENT_PHASE",
    "MEMORY_RETRIEVING_ENRICHMENT_PHASE",
    "MEMORY_RETRIEVED_ENRICHMENT_PHASE",
    "MEMORY_INDEXING_ENRICHMENT_PHASE",
    "MEMORY_INDEXED_ENRICHMENT_PHASE",
    "MEMORY_GRAPH_EXTRACTING_ENRICHMENT_PHASE",
    "MEMORY_SKILL_EXTRACTING_ENRICHMENT_PHASE",
    "MEMORY_INSIGHT_EXTRACTING_ENRICHMENT_PHASE",
    "MEMORY_SKILL_EXTRACTED_ENRICHMENT_PHASE",
    "MEMORY_INSIGHT_EXTRACTED_ENRICHMENT_PHASE",
    "MEMORY_ENRICHMENT_PHASES",
    "MESSAGE_REDACTION_APPLIED_ENRICHMENT_PHASE",
    "REDACTION_PREVIEWED_ENRICHMENT_PHASE",
    "REDACTION_ENRICHMENT_PHASES",
    "RESOURCE_REGISTERING_ENRICHMENT_PHASE",
    "RESOURCE_REGISTERED_ENRICHMENT_PHASE",
    "RESOURCE_DEDUP_REUSED_ENRICHMENT_PHASE",
    "RESOURCE_VERSION_SUPERSEDED_ENRICHMENT_PHASE",
    "RESOURCE_EXTRACTING_ENRICHMENT_PHASE",
    "RESOURCE_EXTRACTED_ENRICHMENT_PHASE",
    "RESOURCE_ENRICHMENT_PHASES",
]
